server:
  port: 8000

spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&maxAllowedPacket=10485760
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false # 不使用hibernate_sequence表来生成主键
    database: mysql
  session:
    store-type: none