server:
  port: 8000
  servlet:
    context-path: /auth

spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB:oauth2}?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&maxAllowedPacket=10485760
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false # 不使用hibernate_sequence表来生成主键
    database: mysql
  session:
    store-type: none
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    url: jdbc:mysql://localhost:3306/?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&maxAllowedPacket=10485760
    user: root
    password: root
    locations: classpath:db/flyway
    schemas: ${DB:oauth2}
    ignore-missing-migrations: false
    ignore-future-migrations: false
    validate-on-migrate: true
    clean-on-validation-error: false
    clean-disabled: false
    baseline-version: 1.0.0
    baseline-on-migrate: false
    out-of-order: false
    installed-by: xiao
