server:
  port: 8010
  servlet:
    context-path: /app
spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB:oauth2_app}?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&maxAllowedPacket=10485760
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false # 不使用hibernate_sequence表来生成主键
    database: mysql
  session:
    store-type: none
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    url: jdbc:mysql://localhost:3306/?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&maxAllowedPacket=10485760
    user: root
    password: root
    locations: classpath:db/flyway
    schemas: ${DB:oauth2_app}
    ignore-missing-migrations: false
    ignore-future-migrations: false
    validate-on-migrate: true
    clean-on-validation-error: false
    clean-disabled: false
    baseline-version: 1.0.0
    baseline-on-migrate: false
    out-of-order: false
    installed-by: xiao

auth:
  server:
    provider:
      local:
        name: local
        client-id: local
        client-secret: 111
        authorize-uri: http://auth-server:8000/auth/oauth/authorize
        access-token-uri: http://auth-server:8000/auth/oauth/token
        user-info-uri: http://auth-server:8000/auth/oauth/userInfo
        redirect-uri: http://localhost:8080/auth/login/local

