spring:
  profiles:
    active: api
    include: local, weixin # 支持的第三方登录认证
server:
  port: 8010
  servlet:
    context-path: /app

auth:
  providers:
    active: local, weixin # 启用的第三方登录认证