server:
  port: 8010
  servlet:
    context-path: /app

auth:
  server:
    provider:
      local:
        name: local
        client-id: local
        client-secret: 111
        authorize-uri: http://auth-server:8000/auth/oauth/authorize
        access-token-uri: http://auth-server:8000/auth/oauth/token
        redirect-uri: http://localhost:8080/auth/login/local

